import Foundation

/// Crash report helper — provides paths to system crash logs and app log directory.
/// macOS automatically saves crash reports to ~/Library/Logs/DiagnosticReports/
/// which CrashReportCollector scans and uploads to Supabase Storage on next launch.
public enum CrashReporter {

    private static let launchTimeKey = "CrashReporter.lastLaunchTime"

    /// App-specific log directory for manual diagnostics.
    private static var logDir: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Logs/NewReader")
    }

    /// Where processed crash reports are moved after uploading.
    private static var processedDir: URL {
        logDir.appendingPathComponent("Processed")
    }

    /// Ensure log directory exists and record this launch time.
    /// Call this early in app startup; after it, CrashReportCollector
    /// can compare file timestamps against `lastLaunchTime` to find new crashes.
    public static func install() {
        let fm = FileManager.default
        try? fm.createDirectory(at: logDir, withIntermediateDirectories: true)
        try? fm.createDirectory(at: processedDir, withIntermediateDirectories: true)
        recordLaunch()
    }

    /// The time of the previous (i.e. this) app launch.
    /// Crash reports with modification dates after this timestamp
    /// were generated by a crash in the *previous* session.
    public static var lastLaunchTime: Date {
        if let saved = UserDefaults.standard.object(forKey: launchTimeKey) as? Date {
            return saved
        }
        return Date.distantPast
    }

    /// Path to the app log directory (for Finder reveal).
    public static var logDirectoryPath: String {
        logDir.path
    }

    /// Path to macOS system crash reports.
    public static var diagnosticReportsPath: String {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Logs/DiagnosticReports")
            .path
    }

    /// Path to the processed-crash-reports directory.
    public static var processedReportsPath: String {
        processedDir.path
    }

    /// Write a diagnostic message to the app log.
    public static func log(_ message: String) {
        let entry = "[\(Date())] \(message)\n"
        let file = logDir.appendingPathComponent("app.log")
        if let data = entry.data(using: .utf8) {
            if FileManager.default.fileExists(atPath: file.path) {
                if let handle = try? FileHandle(forWritingTo: file) {
                    handle.seekToEndOfFile()
                    handle.write(data)
                    try? handle.close()
                }
            } else {
                try? data.write(to: file)
            }
        }
    }

    // MARK: - Private

    private static func recordLaunch() {
        UserDefaults.standard.set(Date(), forKey: launchTimeKey)
    }
}
